config/routes.rb
Rails.application.routes.draw do

  root 'kittens#index'

  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController

  def index
    @kittens = Kitten.all
    @response = HTTParty.get("https://api.flickr.com/services/rest/?method=flickr.photos.search&api_key=#{ENV['FLICKR_KEY']}&tags=kittens&per_page=#{@kittens.length}&format=rest")
    @pics = @response["rsp"]["photos"]["photo"]

    if @kittens.count < 1
      @message = "no kittens to display"
    else
      @message = "#{@kittens.count} kittens found"
    end
  end

  def show
    @kitten = Kitten.find(params[:id])
    if !@kitten
      @header = "no kitten"
    else
      @header = @kitten.name
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)
    if @kitten.save
      redirect_to @kitten, notice: "Kitten Successfully Added!"
    else
      flash[:notice] = @kitten.errors.full_messages.join(', ')
      render action: 'new'
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])
    if @kitten.update(kitten_params)
      redirect_to @kitten, notice: "Kitten Successfully Updated!"
    else
      flash[:notice] = @cutie.errors.full_messages.join(', ')
      render action: 'edit'
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy
    redirect_to kittens_path, notice: "Kitten Successfully Deleted!"
  end

  private

  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/kittens/_kitten_form.html.erb
<%= form_for @kitten do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>

  <%= f.label :age %>
  <%= f.text_field :age %><br>

  <%= f.label :cuteness %>
  <%= f.text_field :cuteness %><br>

  <%= f.label :softness %>
  <%= f.text_field :softness %><br>

  <%= f.submit "Submit" %>
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit <%= @kitten.name %></h2>

<%= render 'kitten_form' %>

<p><%= link_to "Delete #{@kitten.name}", kitten_path(@kitten), method: :delete, data: { confirm: 'Are you certain you want to delete this?' } %></p>

app/views/kittens/index.html.erb
<h1>All the kittens</h1>

<%= @message %>

<% @kittens.each do |kitten|%>
  <li><%= link_to kitten.name, kitten_path(kitten) %> | <%= link_to "Delete?", kitten_path(kitten), method: :delete, data: { confirm: 'Are you certain you want to delete this?' } %> </li>
<% end %>

<p><%= link_to 'Add A Kitten', new_kitten_path %></p>

<% @pics.each do |pic| %>
  <% @cat_url = "https://farm#{pic['farm']}.staticflickr.com/#{pic['server']}/#{pic['id']}_#{pic['secret']}.jpg" %>
<li><img src="<%= @cat_url %>"><br>

<% end %>

app/views/kittens/new.html.erb
<h1>Add A Kitten</h2>

<%= render 'kitten_form' %>

app/views/kittens/show.html.erb
<h1><%= @kitten.name %></h1>
<p>Age: <%= @kitten.age %></p>
<p>Cuteness: <%= @kitten.cuteness %></p>
<p>Softness: <%= @kitten.softness %></p>

<%= link_to "Edit #{@kitten.name}", edit_kitten_path(@kitten) %><br>
<%= link_to "Delete #{@kitten.name}", kitten_path(@kitten), method: :delete, data: { confirm: 'Are you certain you want to delete this?' } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <span class="alerts">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </span>
    
    <%= link_to "Home", kittens_path %>
    <%= yield %>
  </body>
</html>